Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7"
  config.vm.define "centos7-base"
  config.vm.provider "virtualbox" do |v|
    #Needs a reasonable RAM allocation or ClamAV daemon fails first time start
    v.memory = 4096 
    v.cpus = 2
  end

  config.vm.provision "shell",    
    inline: "yum install python-setuptools -y"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../playbook.yml"
  end
end
