---
- hosts: centos7-base
  become: true
  collections: 
    - ch-collections.base
  pre_tasks:
  - name: Updating System Packages Before Ansible Run
    yum:
      name: '*'
      state: latest
  roles:
    - role: RHEL7-CIS
      vars:
        rhel7cis_time_synchronization: chrony
        rhel7cis_time_synchronization_servers: ["169.254.169.123"] #Default VPC source
        rhel7cis_squid_server: true
        rhel7cis_firewall: "iptables"
        #Disable rsyslog/syslog-ng, using cloudwatch
        rhel7cis_rule_4_2_3: false
        rhel7cis_rule_4_2_1_1: false
        rhel7cis_rule_4_2_1_2: false
        rhel7cis_rule_4_2_1_3: false
        rhel7cis_rule_4_2_1_4: false
        rhel7cis_rule_4_2_1_5: false
        rhel7cis_rule_4_2_2_1: false
        rhel7cis_rule_4_2_2_2: false
        rhel7cis_rule_4_2_2_3: false
        rhel7cis_rule_4_2_2_4: false
        rhel7cis_rule_4_2_2_5: false
        rhel7cis_rule_4_3: false
        #Disable GRUB tasks
        rhel7cis_rule_1_4_2: false
        rhel7cis_rule_1_6_1_1: false
        rhel7cis_rule_4_1_3: false
        #Disable Firewall Tasks, we manage this in app deploy
        rhel7cis_rule_3_6_1: false
        rhel7cis_rule_3_6_2: false
        rhel7cis_rule_3_6_3: false
        rhel7cis_rule_3_6_4: false
        rhel7cis_rule_3_6_5: false
        rhel7cis_rule_5_4_4: false
    - epel
    - role: cloudwatch-agent
      vars:
        cwa_conf_json_file_content: "{{ lookup('file', 'files/cloudwatch-config.json') }}"
    - ch_collections.base.cloudwatch_agent_helper
    - ch_collections.base.nagios_nrpe_client
    - clamav
