---
collections:
  - name: https://github.com/companieshouse/ansible-collections.git#ch_collections/base
    version: 0.1.112
    type: git
  - name: community.general
    version: 4.8.0
  - name: ansible.posix
    version: 1.1.1

roles:
  - src: https://github.com/geerlingguy/ansible-role-repo-epel
    name: epel
    version: "1.3.0"
  - src: https://github.com/christiangda/ansible-role-amazon-cloudwatch-agent.git
    name: cloudwatch-agent
  
